### ISSUE TITLE
Add integration with GStreamer 1.16 recipes in openembedded-core/poky and also in meta-gstreamer1.0

### ISSUE THREAD

**Issue by dv1** [Igalia/meta-webkit#109]
GStreamer 1.16 introduced the WPE plugin. In order to build it in Yocto/OE, meta-webkit is needed. Also, a new PACKAGECONFIG has to be added to https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.16.0.bb (and the `--disable-wpe` switch in `EXTRA_OECONF` has to be removed).

However, when I tried that, I got a lot of compilation errors.

Unfortunately, I no longer have the error log. However, it is straightforward to reproduce.

1. Add meta-webkit to your `bblayers.conf`.

2. Add this line to `gstreamer1.0-plugins-bad_1.16.0.bb`:
    `PACKAGECONFIG[wpe] = "--enable-wpe,--disable-wpe,"wpewebkit wpebackend-fdo virtual/egl libxkbcommon"`
    (The PACKAGECONFIG lines in that bitbake recipe are sorted alphabetically)

3. Remove the `--disable-wpe` switch in `EXTRA_OECONF` (also remove "wpe" from the "these plugins have no corresponding library in OE-core or meta-openembedded" comment block to be thorough).

4. Add "wpe" to the gstreamer1.0-plugins-bad PACKAGECONFIG line (for example in your local.conf: `PACKAGECONFIG_append_pn-gstreamer1.0-plugins-bad = " wpe "` - pay attention to the whitespaces surrounding "wpe" !)

Then try to build gstreamer1.0-plugins-bad.

**Comment by philn** [comment]
I found a build issue indeed, should be fixed now, can you check again after back porting https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/commit/5105bc804154144d94bc91a8a912bf1a491270ae ?
