### ISSUE TITLE
Equivalent of Fake KMS in Raspberry

### ISSUE THREAD

**Issue by limbouser** [Igalia/meta-webkit#141]
I'm using a RPi3 and to build an application I had to activate Fake/Full KMS(Legacy doesn't work) in raspi-config of RPi3 and a directory /dev/dri with a file card0 in it was formed. I want to do the same  in RDK. Will the steps in this manual work?

**Comment by philn** [comment]
Can you open a bug report there please? https://github.com/WebPlatformForEmbedded/WPEBackend-rdk
In meta-webkit we manage the integration of the various WPE components, not their actual development.
