### ISSUE TITLE
/dev/sdX doesn't exist

### ISSUE THREAD

**Issue by Chetan2312** [Igalia/meta-webkit#142]
I am using pico-pi-imx8mq board and want to interface it with a 5.5 inch amoled hdmi display by waveshare.
1st I installed the pre-built image of android pie. It is giving lot of distortions on the screen, not working properly.
So I started building the image from git. Have been facing issues such as 
"This script is validated with uuu 1.2.92 version, please align with this version" --while executing ./uuu_imx_android_flash.sh -c 13 -f imx8mq -e -D.
After spending time, I started regenerating files, build u-boot in the same directory. I got following error:
$ ./install_uboot_imx8.sh -b imx8mq-pico-pi -d /dev/sdX
Before run this script, please build u-boot first!
And 
/dev/sdX doesn't exist !!! -- at the end of the line.

Can anyone help me understand this?
I am new to using u-boot tool.

[log file1.txt](https://github.com/Igalia/meta-webkit/files/4197786/log.file1.txt)

**Comment by clopez** [comment]
I don't this its the right place to this bug.
Your problem its not related with meta-webkit layer. It looks something much more lower level related with your BSP or with the one that provided you with that `install_uboot_imx8.sh` script.
Please fill this bug there.
