### ISSUE TITLE
Delete old recipes and just keep the last stable version

### ISSUE THREAD

**Issue by psaavedra** [Igalia/meta-webkit#162]
To keep all the WebKit GTK and WPE recipes (a part of the rest of components) have been manifested like a bad idea. This complicates the CI and there is not a strong justification since the moment that the repository is being branch every time that an new poky version is released.

It could be more simple just to proceed like the others layers just keeping the last stable version for each component.

There is related discussion in this PR: https://github.com/Igalia/meta-webkit/pull/130

**Comment by clopez** [comment]
I did that for WebKitGTK in https://github.com/Igalia/meta-webkit/pull/159

**Comment by psaavedra** [comment]
I  just created a pull request addressing this issue
