### ISSUE TITLE
Changing WPEFramework Cache location

### ISSUE THREAD

**Issue by gil0109** [Igalia/meta-webkit#19]
How do I change the default cache location for WPEFramework?

Currently it is /home/<user>/.cache
root@raspberrypi3:~/.cache# ls -l
-rw-------    1 root     root     227465982 Jul  2 02:48 WPEWebProcess-FSV7KZ
drwx------    3 root     root          1024 Jan  1  1970 cog
drwxr-xr-x    2 root     root          1024 Jul  2 02:47 gstreamer-1.0

I would like to change it to /tmp  (tmpfs location).

**Comment by philn** [comment]
Please report this to WPEFramework: https://github.com/WebPlatformForEmbedded/WPEFramework
