### ISSUE TITLE
Missing dunfell branch

### ISSUE THREAD

**Issue by macabeus** [Igalia/meta-webkit#207]
I think that this repository is missing the branch `dunfell`.
We have branches for older releases, such as `zeus` and `sumo`, but there isn't the branch for `dunfell`, and so we are needing to build using the `master` - and this approach doesn't follow the pattern of others projects.

Related: https://github.com/Igalia/meta-webkit/pull/152#issuecomment-606319947

**Comment by psaavedra** [comment]
Created: https://github.com/Igalia/meta-webkit/tree/dunfell. 


Thanks.
