### ISSUE TITLE
Thud compatibility

### ISSUE THREAD

**Issue by philn** [Igalia/meta-webkit#271]
Some of our users still use the Thud release. Would it be OK to re-enable support for that release?

**Comment by clopez** [comment]
There is a thud branch
When you ask about re-enabling support do you mean if it would be ok to backport patches to the thud branch or if it would be ok to make master compatible with Thud?

**Comment by philn** [comment]
Hum I think backporting newest stable releases to Thud branch, for instance.

**Comment by philn** [comment]
I'll get started on backporting :)

**Comment by philn** [comment]
#272
