### ISSUE TITLE
framebuffer rpi4

### ISSUE THREAD

**Issue by admindotnu** [Igalia/meta-webkit#336]
I am a bit confused about what build options we need to use, if it is possible at all. Documentation is rpi3 orientated.

We are used to use webkit and display directly on the framebuffer of the rpi3.
Is that possible for the rpi4 / cm4 too ?
If yes, what local.conf options do i need to use ?

**Comment by psaavedra** [comment]
Please follow the instructions documented in https://github.com/Igalia/meta-webkit/wiki/RPi#image-with-mesa-vc4-driver-drm-and-wpebackend-fdo-heavy_check_mark and change the MACHINE to `raspberry4-64`. Also notice the warning note referring to work around commented in https://github.com/Igalia/meta-webkit/issues/275#issuecomment-963909594

**Comment by admindotnu** [comment]
Hi @psaavedra 

Will do a test compile soon !. Will close the issue, if needed will reply in this issue again.
