### ISSUE TITLE
Cog: How to check if the GPU is really being used for hardware acceleration?

### ISSUE THREAD

**Issue by Oquirella** [Igalia/meta-webkit#402]
I get really poor performance on pages where svg graphs are being used. (on IMX8MP with vivante graphics driver).

**Comment by nikolaszimmermann** [comment]
I would call the option „lbse“.

**Comment by Oquirella** [comment]
I enable the option, but i didn't see any performance improvements when showing my SVG graphs @nikolaszimmermann. The library i am using is: https://github.com/amcharts/amcharts4

**Comment by Oquirella** [comment]
That's too bad @nikolaszimmermann , i really wanted to test this feature. Is there no nightly or experimental branch where this feature is fully enabled?

**Comment by nikolaszimmermann** [comment]
No not yet, we're working on it to make it happen soon.

**Comment by Oquirella** [comment]
The performance on the svg graphs in chromium is so much better, with cog it is unusable...

**Comment by nikolaszimmermann** [comment]
We're aware of the current limitations and actively work on improvments. If you want want to assist and getting your specific case to work faster, a striped down minimal reduced version of your web page, which exhibits the performance problems, would be helpful.

**Comment by Oquirella** [comment]
My website uses something like this but moving: https://www.amcharts.com/demos-v4/stacked-area-v4/
