### ISSUE TITLE
Any way to build meta-webkit for Yocto Kirkstone ?

### ISSUE THREAD

**Issue by Rutvij-dev** [Igalia/meta-webkit#407]
Hi,
Currently I am able to build meta-webkit for `dunfell`, however need arrived to switch to `krikstone`.

So any port available ?
Any advice to achieve this ?

Appreciate any help.

--
Thanks

**Comment by marvinfrankeengram** [comment]
Although there is no kirkstone branch (yet?), using the main branch of this layer works for me. Note that they are still working on it and changes might break things.
In the honister branch, they claim to be compatible with kirkstone, haven't testet that though. But I guess, changes there are probably more unlikely to break things, so it may be worth a try.

**Comment by aahmed7** [comment]
The master branch has the compat for kirkstone in conf/layer.conf, so it should build

**Comment by Rutvij-dev** [comment]
Yes it did work , Thanks for your inputs
