### ISSUE TITLE
cog: url, webpage does not occupy full display screen / canvas

### ISSUE THREAD

**Issue by vijaynkamble86** [Igalia/meta-webkit#408]
Hello WPE Webkit Team,

I have ported latest meta-webkit layer and using wpebackend as wpebackend-fdo.  And I am launching url / webpage using below command - 

cog https://www.google.com

But the Google Browser is getting rendered on part of the screen, I mean its not occupying the whole display / canvas. 

Is there way, I can launch the Google Browser which occupies full screen(irrespective of the type of the screen..?)

HW Used - QCOM SoC
OS - Yocto Dunfell

Could you please help..?

Cheers,
Vijay

**Comment by philn** [comment]
Have you tried `COG_PLATFORM_WL_VIEW_FULLSCREEN` as documented in https://igalia.github.io/cog/platform-wl.html ?
