### ISSUE TITLE
Start Cog as Service

### ISSUE THREAD

**Issue by WalterPrech** [Igalia/meta-webkit#486]
I made an embedded Linux with Yocto and meta-webkit (Weston, IMAGE_INSTALL:append = " wpewebkit cog")

In weston.ini I use shell=kiosk-shell.so

All works well and I can start cog from the command line with 'cog --platform=wl www.example.com'.

I made a bash script to start Cog and it works from the command line.

But if I try to start the bash script from a service, the browser don't start.

Has anyone a hint how to do this?

**Comment by clopez** [comment]
Guessing: This is likely related to the environment and the startup ordering.

The systemd unit that starts cog should wait until weston/wayland is fully started and then it should define the `WAYLAND_DISPLAY` and `XDG_RUNTIME_DIR` environment variables accordingly.

Maybe an alternative approach is starting Cog as a weston/wayland startup script so it inherits the environment and starts after it.

For example in /etc/weston.ini you can set something like this

```
[autolaunch]
path=/usr/local/bin/cog-init.sh
```

Refs: https://man.archlinux.org/man/weston.ini.5.en#AUTOLAUNCH_SECTION
