### ISSUE TITLE
Re-add the 0001-FELightningNEON.cpp-fails-to-build-NEON-fast-path-se.patch

### ISSUE THREAD

**Issue by psaavedra** [Igalia/meta-webkit#497]
**Is your feature request related to a problem? Please describe.**

Related to [FELightningNEON.cpp fails to build, NEON fast path seems unused](https://bugs.webkit.org/show_bug.cgi?id=241182)

**Describe the solution you'd like**

Re-add the [0001-FELightningNEON.cpp-fails-to-build-NEON-fast-path-se.patch](https://github.com/Igalia/meta-webkit/blob/830404acbb3279a2f67bfc10a526428523518dbb/recipes-browser/wpewebkit/wpewebkit/0001-FELightningNEON.cpp-fails-to-build-NEON-fast-path-se.patch) removed in https://github.com/Igalia/meta-webkit/pull/496

**Describe alternatives you've considered**

* The alternative is just left this patch out and ignore it.

**Additional context**

* Useful for ARM NEON boards.

**Comment by aperezdc** [comment]
The NEON fast path for the `feLighting` filter has been re-added in [272873@main](https://commits.webkit.org/272873@main) (bug [#267349](https://bugs.webkit.org/show_bug.cgi?id=267349)). This is part of the 2.44.x release branch, so we do _not_ need to do anything in this regard.
