### ISSUE TITLE
WSA-2019-0001 vulnerabilities were discovered in WebKitGTK+ and WPE WebKit before 2.22.6 and 2.22.4

### ISSUE THREAD

**Issue by psaavedra** [Igalia/meta-webkit#67]
https://webkitgtk.org/security/WSA-2019-0001.html

**Comment by psaavedra** [comment]
build success: https://gitlab.com/saavedra.pablo/meta-perf-browser/pipelines/46925155

**Comment by philn** [comment]
In commit messages you can put "Fixes #number" to automatically close issues when a PR is merged :)
