### ISSUE TITLE
WPEwebkit, not master?

### ISSUE THREAD

**Issue by woutervanh** [Igalia/meta-webkit#8]
Is there a reason why you don't take the master branch of wpewebkit?

**Comment by clopez** [comment]
Lack of time. Feel free to send a patch (after testing it and checking it works of course)

**Comment by woutervanh** [comment]
I'm trying, but it has compile errors :(

**Comment by clopez** [comment]
This should be fixed already (in master).
So I'm closing this issue.
Let me know if you think its not fixed.
