### ISSUE TITLE
Could not inherit file classes/cmake_qt5.bbclass

### ISSUE THREAD

**Issue by HowardACornwell** [Igalia/meta-webkit#87]
When following the steps to build for RPi ([link](https://github.com/Igalia/meta-webkit/wiki/RPi)), `bitbake core-image-base` throws the following error:

```
ERROR: ParseError at /files/yocto-rpi-wpe/meta-webkit/recipes-qt/qt-wpe-simple-browser/qt-wpe-simple-browser_0.1.bb:16: Could not inherit file classes/cmake_qt5.bbclass
````

**Comment by philn** [comment]
Did you enable meta-qt5 as mentioned in the README?

**Comment by HowardACornwell** [comment]
My mistake, the build is now running. Thanks for the quick response.
